// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_JesusBonilla.DAL;

#nullable disable

namespace P1_AP1_JesusBonilla.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251009123514_CambiosEnLosModelos")]
    partial class CambiosEnLosModelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_JesusBonilla.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("EntradaId");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("P1_AP1_JesusBonilla.Models.EntradasHuacalesDetalles", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("TipoId");

                    b.ToTable("EntradasHuacalesDetalles");
                });

            modelBuilder.Entity("P1_AP1_JesusBonilla.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencias")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Rojo Grande",
                            Existencias = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Rojo Mediano",
                            Existencias = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Rojo Pequeño",
                            Existencias = 0
                        },
                        new
                        {
                            TipoId = 4,
                            Descripcion = "Verde Grande",
                            Existencias = 0
                        },
                        new
                        {
                            TipoId = 5,
                            Descripcion = "Verde Mediano",
                            Existencias = 0
                        },
                        new
                        {
                            TipoId = 6,
                            Descripcion = "Verde Pequeño",
                            Existencias = 0
                        });
                });

            modelBuilder.Entity("P1_AP1_JesusBonilla.Models.EntradasHuacalesDetalles", b =>
                {
                    b.HasOne("P1_AP1_JesusBonilla.Models.EntradasHuacales", "entradaHuacal")
                        .WithMany("EntradasHuacalesDetalles")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_AP1_JesusBonilla.Models.TiposHuacales", "TipoHuacal")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoHuacal");

                    b.Navigation("entradaHuacal");
                });

            modelBuilder.Entity("P1_AP1_JesusBonilla.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
